name: autotest_telnix
on:
    push:
        branches: [main]
jobs:
    Run_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 
              uses: actions/setup-node@v2
              with:
                  node-version: 16.16.0
                  cache: "npm"
            - name: install all dependencies
              run: npm i
            - name: instal formatter
              run: chmod +x cucumber-json-formatter
            - name: run test
              run: npm run cypress:run
            - name: Generate reports
              if: always()
              run: npm run cypress:report
            - name: Upload artifact cucumber-report
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: cucumber-report
                  path: ./reports/cucumber-htmlreport 
            - name: Deploy to pages
              if: always()
              uses: peaceiris/actions-gh-pages@v3.7.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: reports/cucumber-htmlreport/ 